### ISSUE TITLE
Deletion of rrs3 won't delete everything

### ISSUE THREAD

**Issue by PeterMengQiWu** [razee-io/RemoteResourceS3#26]
**Describe the bug**
Deleting a RemoteResourceS3 in a namespace deletes the deployments, but doesn't delete pods and replicasets

**To Reproduce**
1. Apply this yaml file:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: foo-creds-1
  labels:
    app: foo
    chart: foo-chart
    release: foo
    heritage: Tiller
data:
  sample_password: anhwcHpCTGZkWjBt

---
apiVersion: v1
kind: Secret
metadata:
  name: foo-creds-2
  labels:
    app: foo
    chart: foo-chart
    release: foo
    heritage: Tiller
data:
  another_sample_password: QlptdUxwNTRtQXVC

---

apiVersion: v1
kind: Secret
metadata:
  name: foo-creds-3
  labels:
    app: foo
    chart: foo-chart
    release: foo
    heritage: Tiller
data:
  password1: ejNBRmFPaDVUcGhY
  password2: UTJvTllESlJ2V0pq
  password3: ZlZsMDVXMXZnVm5v
  password4: QXZuOVExbUF5U3VY
  password5: ekNqYkwwUGJXR2xZ
  password6: V0dZYkFxZlcxckR4
  password7: SjM1N0RoU3JJbGtk
  password8: dE9jUXRDSVgwTnJW
  password9: RmpCbjRjamRUcndK
  password10: MnA5T0tGb0RMT2JX
  password11: M1NTRVMwNkM2dmZH

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-deployment
  labels:    
    app: foo
    chart: foo-chart
    release: foo
    heritage: Tiller
spec:
  template:
    metadata:
      annotations:
        checksum/confmap_bootstrap: f96ef3241bef8018a644c4c61e6e49acedef32416e309e7d0bccbaaed56d7248
      labels:
        app: foo
        release: foo
        waca-app: waca-auth
    spec:
      restartPolicy: Always
      hostname: auth
      securityContext:
        fsGroup: 2000
      containers:
        - name: auth
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: "/data"
              name: datadir
            - mountPath: "/bootstrap/creds/other"
              name: "foo-creds-3"
            - mountPath: "/bootstrap/creds/foo-creds-1"
              name: "foo-creds-1"
            - mountPath: "/bootstrap/creds/foo-creds-2"
              name: "foo-creds-2"
          env:
            - name: BOOTSTRAP_FILE
              value: /bootstrap/directory.ldif
            - name: TZ
              value: ""
      volumes:
        - name: datadir
          emptyDir: {}
        - name: "foo-creds-3"
          secret:
            secretName: foo-creds-3
            defaultMode: 0440
        - name: "foo-creds-1"
          secret:
            secretName: foo-creds-1
            defaultMode: 0440
        - name: "foo-creds-2"
          secret:
            secretName: foo-creds-2
            defaultMode: 0440
  replicas: 1
  strategy:
    type: Recreate
```
2. Have a RemoteResourceS3 url to this file
3. Apply the RemoteResourceS3
4. Wait for the pod to stand up, then delete RemoteResourceS3

**Expected behavior**
Deleting a RemoteResourceS3 should delete everything

**Kubernetes Version (kubectl version):**
Client Version: 1.16.0
Server Version: 1.15.3
